// <auto-generated />
using System;
using DBFIRST_Cities3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBFIRST_Cities3.Migrations
{
    [DbContext(typeof(WorldContext))]
    partial class WorldContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBFIRST_Cities3.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CompeleteNameId")
                        .HasColumnType("int")
                        .HasColumnName("compeleteNameID");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("countryId");

                    b.Property<int?>("HumidityId")
                        .HasColumnType("int")
                        .HasColumnName("humidityID");

                    b.Property<int?>("LatId")
                        .HasColumnType("int");

                    b.Property<int?>("LongId")
                        .HasColumnType("int");

                    b.Property<int?>("PopulationId")
                        .HasColumnType("int")
                        .HasColumnName("populationID");

                    b.Property<int?>("TempId")
                        .HasColumnType("int")
                        .HasColumnName("TempID");

                    b.Property<DateTime>("modifytime")
                        .HasColumnType("datetime2");

                    b.HasKey("CityId");

                    b.HasIndex("LatId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("DBFIRST_Cities3.Models.CompeleteName1", b =>
                {
                    b.Property<int?>("CompeleteNameId")
                        .HasColumnType("int")
                        .HasColumnName("CompeleteNameID");

                    b.Property<string>("CompeleteNameName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("CompeleteName_Name")
                        .IsFixedLength();

                    b.ToTable("CompeleteName1", (string)null);
                });

            modelBuilder.Entity("DBFIRST_Cities3.Models.Country1", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountryId");

                    b.ToTable("COUNTRY1", (string)null);
                });

            modelBuilder.Entity("DBFIRST_Cities3.Models.Humidity", b =>
                {
                    b.Property<int>("Humidityid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Humidityid"));

                    b.Property<int?>("Humidity1")
                        .HasColumnType("int")
                        .HasColumnName("Humidity");

                    b.HasKey("Humidityid");

                    b.ToTable("Humiditys");
                });

            modelBuilder.Entity("DBFIRST_Cities3.Models.Latitude", b =>
                {
                    b.Property<int>("LatitudeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LatitudeId"));

                    b.Property<string>("Latitude1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Latitude");

                    b.HasKey("LatitudeId");

                    b.ToTable("Latitudes");
                });

            modelBuilder.Entity("DBFIRST_Cities3.Models.Longitude", b =>
                {
                    b.Property<int>("LongitudeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LongitudeId"));

                    b.Property<string>("Longitude1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Longitude");

                    b.HasKey("LongitudeId");

                    b.ToTable("Longitudes");
                });

            modelBuilder.Entity("DBFIRST_Cities3.Models.Population", b =>
                {
                    b.Property<int?>("Population1")
                        .HasColumnType("int")
                        .HasColumnName("Population");

                    b.Property<int?>("PopulationId")
                        .HasColumnType("int");

                    b.ToTable("Populations");
                });

            modelBuilder.Entity("DBFIRST_Cities3.Models.Temperature", b =>
                {
                    b.Property<int>("TempId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TempID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TempId"));

                    b.Property<int?>("Temperature1")
                        .HasColumnType("int")
                        .HasColumnName("Temperature");

                    b.HasKey("TempId");

                    b.ToTable("Temperatures");
                });

            modelBuilder.Entity("DBFIRST_Cities3.Models.City", b =>
                {
                    b.HasOne("DBFIRST_Cities3.Models.Latitude", "Lat")
                        .WithMany("Cities")
                        .HasForeignKey("LatId")
                        .HasConstraintName("FK_Cities_Latitudes");

                    b.Navigation("Lat");
                });

            modelBuilder.Entity("DBFIRST_Cities3.Models.Latitude", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
